image:
  name: "ubuntu:latest"

run-test:
  script:
    - apt-get update -y && apt-get install curl python3 python3-pip python3-venv -y
    - export LANG=C.UTF-8
    - python3 -m venv venv
    - source venv/bin/activate
    - rm -rf .pio
    - pip install --upgrade pip setuptools wheel
    - pip install platformio
    - cp src/main.cpp.gitlab-ci_yml src/main.cpp
    - pio init --board nodemcuv2
    - pio run
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://vmi273874.contaboserver.net:6443/api/v4/projects/4/trigger/pipeline
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://vmi273874.contaboserver.net:6443/api/v4/projects/8/trigger/pipeline
