image:
  name: "sglahn/platformio-core:latest"
  entrypoint: [""]

run-test:
  script:
    - cp src/main.cpp.gitlab-ci_yml src/main.cpp
    - platformio run
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.example.com/api/v4/projects/4/trigger/pipeline